### ISSUE TITLE
cannot import name 'KEYS'

### ISSUE THREAD

**Issue by JeffLIrion** [JeffLIrion/homeassistant_native_firetv#25]
https://community.home-assistant.io/t/native-support-for-fire-tv/64448/248?u=jefflirion

> Just tried the lastest master firetv.py and get the following error.

```
Error loading custom_components.media_player.firetv. Make sure all dependencies are installed

Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/homeassistant/loader.py", line 117, in _load_file module = importlib.import_module(path) File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "&lt;frozen importlib._bootstrap&gt;", line 994, in _gcd_import File "&lt;frozen importlib._bootstrap&gt;", line 971, in _find_and_load File "&lt;frozen importlib._bootstrap&gt;", line 955, in _find_and_load_unlocked File "&lt;frozen importlib._bootstrap&gt;", line 665, in _load_unlocked File "&lt;frozen importlib._bootstrap_external&gt;", line 678, in exec_module File "&lt;frozen importlib._bootstrap&gt;", line 219, in _call_with_frames_removed File "/config/custom_components/media_player/firetv.py", line 162, in &lt;module&gt; class FireTVDevice(MediaPlayerDevice): File "/config/custom_components/media_player/firetv.py", line 165, in FireTVDevice from firetv import KEYS ImportError: cannot import name 'KEYS'
```

**Comment by JeffLIrion** [comment]
**Problem:** You have an old version of the `firetv` package installed. 

**Solution:** In your `<configuration>/deps` folder (and all subfolders), delete all `firetv` and `firetv*` folders and restart Home Assistant. HA will install the latest version of `firetv` 1.0.8 from GitHub.

**Comment by Fma965** [comment]
this doesn't actually fix the issue.

**Comment by Fma965** [comment]
`Error loading custom_components.media_player.firetv. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/loader.py", line 117, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/media_player/firetv.py", line 174, in <module>
    class FireTVDevice(MediaPlayerDevice):
  File "/config/custom_components/media_player/firetv.py", line 177, in FireTVDevice
    from firetv import KEYS
ImportError: cannot import name 'KEYS'`
i don't have any firetv folders in deps

**Comment by JeffLIrion** [comment]
@Fma965 You need to look in the subfolders.  

```bash
core-ssh:~# cd /config/deps/lib/python3.6/site-packages/
core-ssh:/config/deps/lib/python3.6/site-packages# ls
__pycache__                                         firetv-1.0.8.dist-info                              pyaes-1.6.1.dist-info
adb                                                 libusb1-1.6.6.dist-info                             pytuya
adb_homeassistant-1.3.1.dist-info                   libusb1.py                                          pytuya-7.0.dist-info
adb_messenger                                       pure_python_adb_homeassistant-0.1.6.dev0.dist-info  usb1
firetv                                              pyaes
```

**Comment by Fma965** [comment]
I have, I still dont have any.

**Comment by JeffLIrion** [comment]
I posted some more detailed instructions above.  It seems that HA version 0.87 doesn't install the dependencies for you, so you might need to install the `firetv` package yourself.

**Comment by Fma965** [comment]
I dont believe I can do that on hass.io? Can I?

**Comment by JeffLIrion** [comment]
You have to do it on a different machine and copy the files over.

**Comment by Fma965** [comment]
Yes, sorry, I missed that bit till after I replied. It's late here but will
give it a try tomorrow and report back.

**Comment by Fma965** [comment]
so i did the pip command now i have this? where does this go?

![image](https://user-images.githubusercontent.com/1707290/52860565-b44de480-3127-11e9-87c4-22b719d38ffe.png)

**Comment by JeffLIrion** [comment]
Copy and paste all of that to your `<configuration>/deps/lib/python3.6/site-packages/` folder.

**Comment by Fma965** [comment]
perfect thanks. its not complaining about that error now, haven't got it tested on a actual fire tv yet though.
