### ISSUE TITLE
errors with latest firetv.py custom_component

### ISSUE THREAD

**Issue by hooray4me** [JeffLIrion/homeassistant_native_firetv#26]
2019-03-07 21:21:49 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.firetv.media_player. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/home/rob/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rob/.homeassistant/custom_components/firetv.py", line 12, in <module>
    from homeassistant.components.media_player import (
ImportError: cannot import name 'SUPPORT_TURN_OFF'

**Comment by hooray4me** [comment]
finally got to the bottom of the hass thread and saw you were stepping away. Nevermind.
