### ISSUE TITLE
Don't Get the ADBKey Files

### ISSUE THREAD

**Issue by TexanScot** [JeffLIrion/homeassistant_native_firetv#5]
Following the guide I successfully installed Android Studio on my Mac however I seem to have done something wrong as I don't see the ADBkey files being created on my machine. I have listed below the commands and output that I received.

```
$ ./adb connect 192.168.10.163
adb server version (32) doesn't match this client (40); killing...
* daemon started successfully
failed to authenticate to 192.168.10.163:5555
```
At this point I realized that I need to stop and restart the server:

```
$ ./adb kill-server
$ ./adb start-server
* daemon not running; starting now at tcp:5037
* daemon started successfully

$ ./adb connect 192.168.10.163
failed to authenticate to 192.168.10.163:5555
```
At this point I received some dialog on the TV providing some kind of RSA key? and a message "Always trust this computer? (I think! - I clicked the box to say yes and the message disappeared).

```
./adb devices
List of devices attached
192.168.10.163:5555	device
```

I don't see the adbkey or adbkey.pub files on my computer, presumably because of the 'failed to authenticate' response when I tried to connect. However when I repeat the connect command I get the message that I'm already connected:

```
$ ./adb connect 192.168.10.163
already connected to 192.168.10.163:5555
```
I tried killing and restarting the server again however I still receive the same message. Could you Kindly point out where I have gone wrong and the steps that I need to take to correctly generate the necessary files. 

Many thanks in advance.

**Comment by TexanScot** [comment]
OK, on further reading of add documentation I noted that the key files should be stored in the $HOME/.android folder.

> By default key pairs generated by the adb server are stored in the following key store directories as adbkey (private key) and adbkey.pub (public key):
> 
> Linux and Mac: $HOME/.android.

Looking in this folder I do indeed see adbkey and adbkey.pub files however they are timestamped from May of last year (I'm really not sure how these were created - possibly when I tried installing OpenVPN on the firetv stick?). I copied these files into my HA config folder however and restarted HA. Relevant output from the log file is shown below:

```
2018-09-16 13:03:43 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.family_room_fire_tv, old_state=None, new_state=<state media_player.family_room_fire_tv=unavailable; friendly_name=Family Room Fire TV, supported_features=23357 @ 2018-09-16T13:03:43.507101-05:00>>

2018-09-16 13:03:50 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform firetv is taking over 10 seconds.
2018-09-16 13:04:40 ERROR (MainThread) [homeassistant.components.media_player] Setup of platform firetv is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2018-09-16 13:04:41 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.family_room_receiver, old_state=<state media_player.family_room_receiver=off; friendly_name=Family Room Receiver, supported_features=18828 @ 2018-09-16T13:03:40.576838-05:00>, new_state=<state media_player.family_room_receiver=on; volume_level=0.6799999999999999, is_volume_muted=False, source=AV7, source_list=['AUDIO1', 'AUDIO2', 'AUDIO3', 'AUDIO4', 'AV1', 'AV2', 'AV3', 'AV5', 'AV6', 'AV7', 'AirPlay', 'FireTV', 'MULTI CH', 'NET RADIO', 'PHONO', 'Pandora', 'Rhapsody', 'SERVER', 'SiriusXM', 'TUNER', 'USB', 'V-AUX', 'iPod (USB)'], friendly_name=Family Room Receiver, supported_features=18828 @ 2018-09-16T13:04:41.483782-05:00>>

2018-09-16 13:04:59 WARNING (SyncWorker_3) [custom_components.media_player.firetv] Could not connect to Fire TV at 192.167.10.163:5555
```
Any guidance on how to proceed would be greatly appreciated!

**Comment by JeffLIrion** [comment]
Make sure you're not connected to your Fire TV from your computer. I believe only 1 ADB connection is allowed at a time.

**Comment by JeffLIrion** [comment]
Yeah, run the command that you used before (`./adb kill-server`) prior to starting Home Assistant.

**Comment by TexanScot** [comment]
OK, here is what I did.

1) Shutdown HA by stopping the container.

2) Connected to the firetv from terminal.

```
$ ./adb kill-server
$ ./adb start-server
* daemon not running; starting now at tcp:5037
* daemon started successfully
$ ./adb connect 192.168.10.163
connected to 192.168.10.163:5555
$ ./adb devices
List of devices attached
192.168.10.163:5555	device

$ ./adb kill-server
```
3) Restarted the HA container - log output is as before.

I have both the adbkey and adbkey.pub in my HA config folder and my configuration.yaml container the following:

```
  - platform: firetv
    name: Family Room firetv
    host: 192.167.10.163
    adbkey: "/config/adbkey"
```

Is there any way of checking whether the 'old' key files are those that the firetv presently expects or alternatively is there a way to remove keys from the Mac and firetv and start over?

**Comment by JeffLIrion** [comment]
This might be easier to debug in the Python interactive shell than in Home Assistant.  I'd suggest doing the following.  

1. Make a Python virtual environment
2. In that virtual environment:

   ```
   pip install pycryptodome rsa
   pip install https://github.com/JeffLIrion/python-adb/zipball/master
   ```

3. Run the following Python commands:

   ```python
   from adb import adb_commands
   from adb.sign_pythonrsa import PythonRSASigner
   from adb.adb_protocol import InvalidChecksumError

   serial = '192.167.10.163:5555'
   adbkey = '<path to your adbkey>'

   signer = PythonRSASigner.FromRSAKeyPath(adbkey)

   conn = adb_commands.AdbCommands().ConnectDevice(serial=serial, rsa_keys=[signer])
   ```

That should let you know whether or not your key works.

**Comment by JeffLIrion** [comment]
That's an odd error.  Try this (in your virtual environment):

```bash
pip uninstall rsa
pip install rsa==3.4.2
```

And then repeat the commands in the shell, or run the script.  

Also, if you copy / move your .android folder (e.g., `mv $HOME/.android $HOME/backup.android`), I assume you can retry connecting and it will make a new key for you.

**Comment by TexanScot** [comment]
Same error.

```
(python36) $ pip install rsa==3.4.2
Collecting rsa==3.4.2
  Downloading https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 145kB/s 
Requirement already satisfied: pyasn1>=0.1.3 in /Users/Alan/Software/Anaconda/envs/Python36/lib/python3.6/site-packages (from rsa==3.4.2) (0.4.4)
Installing collected packages: rsa
Successfully installed rsa-3.4.2
```
Python script is:
```
import adb
from adb.sign_pythonrsa import PythonRSASigner
from adb.adb_protocol import InvalidChecksumError

serial = '192.167.10.163:5555'
adbkey = "/Users/alastair/software/home-assistant/development/current_dev/adbkey"

signer = PythonRSASigner.FromRSAKeyPath(adbkey)

conn = adb_commands.AdbCommands().ConnectDevice(serial=serial, rsa_keys=[signer])
```
Console output:
```
Traceback (most recent call last):
  File "/Applications/PyCharm Edu.app/Contents/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm Edu.app/Contents/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm Edu.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/alastair/PycharmProjects/untitled1/firetv.py", line 10, in <module>
    conn = adb_commands.AdbCommands().ConnectDevice(serial=serial, rsa_keys=[signer])
NameError: name 'adb_commands' is not defined
```
I do appreciate the time that you are spending on trying to help me.

Many thanks!

**Comment by JeffLIrion** [comment]
In that case, I'd suggest backing up your key, creating a new one, and trying the new one in Home Assistant.  

Also, is this the correct path for your adbkey file?  

> ```
>   - platform: firetv
>     name: Family Room firetv
>     host: 192.167.10.163
>     adbkey: "/config/adbkey"
> ```

Shouldn't your configuration be:

```yaml
  - platform: firetv
    name: Family Room firetv
    host: 192.167.10.163
    adbkey: "/Users/alastair/software/home-assistant/development/current_dev/adbkey"
```

**Comment by TexanScot** [comment]
I'm running HA in a docker container. The current_dev folder is mapped to the /config folder within the docker container. I can attach to the container and see the keys within the config folder. 
```
root@hass:/usr/src/app# ls -l /config
total 45444
-rw-------  1 root root     1704 Sep 16 14:10 adbkey
-rw-r--r--  1 root root      722 Sep 16 14:10 adbkey.pub
```
Are the permissions on the adbkey file ok? Looks like it to me but I'm certainly not a Unix guru. Assuming they are this would seem to indicate that the data that HA reads from the file is not being accepted by the fire stick. Stupid question perhaps, but is there a way to confirm that the key stored on the firetv is corresponds to the one that HA is presenting?

I'll try regenerating the keys one more time though it doesn't seem to be helping.

**Comment by JeffLIrion** [comment]
Try restarting the Fire TV stick and see if that helps.

**Comment by JeffLIrion** [comment]
I looked over this issue again and I noticed that in the first post the IP address of the Fire TV that you successfully connected to was 192.168.10.163, but in all subsequent posts the IP address is 192.167.10.163. Is that the root of the problem?

**Comment by TexanScot** [comment]
@JeffLIrion 

Hard to believe that it was something so simple and stupid! I corrected the IP address and the firetv now loads correctly. Thanks for spotting the typo and many, many thanks for taking the time to work with me so patiently.

Not only do I appreciate that you did so but I also appreciate all that you are doing for the HA community.
